name: weekendry
description: A hiking event organization app with driver-rider matching

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  
  # Firebase Integration
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  
  # Location Services
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  
  # Authentication
  google_sign_in: ^6.2.1
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  
  # Utilities
  uuid: ^4.2.2
  intl: ^0.19.0
  url_launcher: ^6.2.2
  
  # Deep Linking
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/